FinanceApp.Presentation/ViewModels/PaymentViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using FinanceApp.Core.Models;

namespace FinanceApp.Presentation.ViewModels
{
    public class PaymentViewModel
    {
        public Service Service { get; set; }
        public User User { get; set; }
    }
}

FinanceApp.Presentation/Controllers/FinanceController.cs
using System.Formats.Asn1;
using FinanceApp.Core.Models;
using FinanceApp.Core.Dtos;
using FinanceApp.Core.Repositories;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.IdentityModel.Tokens;
using Microsoft.AspNetCore.Identity;
using FinanceApp.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using FinanceApp.Core.Services;
using System.Security.Claims;
using FluentValidation;
using FinanceApp.Infrastructure.Services;

namespace FinanceApp.Controllers;

[Authorize]
public class FinanceController : Controller
{
    private IBillService billService;
    private IServiceService addserviceService;
    private IServiceRepository serviceRepository;
    private readonly UserManager<User> userManager;

    private readonly IValidator<ServiceDto> serviceValidator;
    private readonly IServiceService serviceService;
    private readonly IUserService userService;
    public FinanceController(IBillService billService, IServiceRepository serviceRepository, UserManager<User> userManager, IServiceService serviceService, IUserService userService, IValidator<ServiceDto> serviceValidator, IServiceService addserviceService)
    {
        this.userManager = userManager;
        this.serviceService = serviceService;
        this.billService = billService;
        this.serviceRepository = serviceRepository;
        this.userService = userService;
        this.serviceValidator = serviceValidator;
        this.addserviceService = addserviceService;
    }

    [HttpGet]
    public async Task<IActionResult> History()
    {
        return View(await billService.History(User));
    }


    public async Task<IActionResult> Delete(int id)
    {
        await billService.DeleteAsync(id);

        return RedirectToAction("History");
    }

    [HttpGet]
    public async Task<IActionResult> Update(int id)
    {
        try
        {
            var bill = await billService.GetByIdAsync(id);

            return base.View(model: bill);
        }

        catch (NullReferenceException)
        {
            return RedirectToAction("NotFound", "Home");
        }

    }

    [HttpPost]

    public async Task<IActionResult> Update(Bill bill)
    {

        await billService.UpdateAsync(bill);

        return RedirectToAction("History");
    }

    [AllowAnonymous]
    [HttpGet]
    public async Task<IActionResult> Services()
    {
        return View(await serviceRepository.GetAll());
    }

    [HttpGet]
    public async Task<IActionResult> Payment(int id)
    {
        return View(await serviceService.Payment(User, id));
    }

    [HttpPost]
    public async Task<IActionResult> Bill(int id)
    {
        var service = await serviceRepository.GetById(id);

        var user = await userManager.GetUserAsync(User);

        var bill = await billService.CreateAsync(service, user, 0);

        return View(bill);

    }

    [HttpPut]
    public async Task<IActionResult> Accept([FromBody] double amount)
    {
        var userId = User.FindFirst(ClaimTypes.NameIdentifier)?.Value!;
        await userService.ChangeBalance(userId, -amount);
        await billService.UpdateAmountSpent(userId, amount);
        return Ok();
    }

    [HttpGet]
    public IActionResult AddService()
    {

        return View();
    }


    [HttpPost]
    public async Task<IActionResult> Search(string service)
    {
        var result = await serviceService.Search(service);

        return View("Services", result);
    }


    [HttpPost]
    [Authorize(Roles = "Admin")]
    public async Task<IActionResult> AddService(ServiceDto serviceDto)
    {
        try
        {
            var result = serviceValidator.Validate(serviceDto);
            if (result.IsValid == false)
            {
                foreach (var error in result.Errors)
                {
                    ModelState.AddModelError(
                        key: error.PropertyName,
                        errorMessage: error.ErrorMessage
                    );
                }
                return View("AddService");
            }
            await serviceService.Add(serviceDto);
            return RedirectToAction("Services");
        }
        catch (Exception ex)
        {
            return RedirectToAction("Error", "ErrorPage", new { message = ex.Message });
        }
    }
    [HttpDelete]
    public async Task<IActionResult> DeleteUserService(int id)
    {
        await this.serviceService.DeleteServiceAsync(id);

        return base.Ok();
    }

    [HttpGet]
    public async Task<IActionResult> SearchByAbonentNumber(int abonentNumber)
    {
        var result = await serviceService.SearchByAbonentNumber(abonentNumber);

        return View("History", result);
    }


}

FinanceApp.Presentation/Views/Finance/AddService.cshtml
@model ServiceDto

@{
    ViewData["Title"] = "Add Service";
}

<h2>@ViewData["Title"]</h2>

@if (ViewData.ModelState.IsValid)
{
    <p>Service added successfully.</p>
}
else
{
    <div class="alert alert-danger" role="alert">
        <strong>Error:</strong> There were some validation errors.
    </div>
}

<form enctype="multipart/form-data" asp-controller="Finance" asp-action="AddService" method="post">
    
    <div class="text-danger" asp-validation-summary="All"></div>

    <div class="form-group">
        <label asp-for="@Model.ServiceImageUrl">Service ImageUrl:</label>
       <input asp-for="@Model.ServiceImageUrl" class="form-control-file" accept="image/*" type = "file">
    </div>

    <div class="form-group">
        <label asp-for="@Model.ServiceName">Service Name:</label>
        <input asp-for="@Model.ServiceName" class="form-control"></input>
    </div>

    <div class="form-group">
        <label asp-for="@Model.ServiceCost">Service Cost:</label>
        <input type="number" asp-for="@Model.ServiceCost" class="form-control"></input>
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>

FinanceApp.Presentation/Views/Finance/Bill.cshtml
@model Bill
<br>
<br>
<br>
<br>

<div class="invoice-box">
    <table>
        <tr class="top">
            <td colspan="2">
                <table>
                    <tr>
                        <td class="title">
                            <img src="~/@Model.Service.ImageUrl" style="width: 100%; max-width: 300px" />
                        </td>

                        <td>
                            Invoice #: @Model.Id <br />
                            Created: @Model.PayDate.ToString("MMMM d yyyy") <br />
                        </td>
                    </tr>
                </table>
            </td>
        </tr>

        <tr class="information">
            <td colspan="2">
                <table>
                    <tr>
                        <td>
                            Name: @Model.User.UserName<br>
                            Age: @Model.User.Age<br>
                            Email: @Model.User.Email
                        </td>
                    </tr>
                </table>
            </td>
        </tr>

        <tr class="heading">
            <td>Information</td>

            <td>Price</td>
        </tr>

        <tr class="item">
            <td>Service cost</td>
            <td>$@(Model.Service.ServiceCost)</td>
        </tr>
        <tr>
            <td>
                Balance: $<span id="userBalance">@Model.User.Balance</span><br>
            </td>
        </tr>

        <tr class="item">
            <td>Enter your payment</td>
            <td>
                <input id="userPayment" type="number" min="0" step="0.01" placeholder="Enter your payment" />
            </td>
        </tr>

        <tr class="total">
            <td></td>
            <td><br>
                <button onclick="Accept(document.getElementById('userPayment').value)">Accept</button>
                <br>
                <span id="errorMessage" style="color: red;"></span>
            </td>
        </tr>
    </table>
</div>

<script>
    function Accept() {
        var userPaymentInput = document.getElementById('userPayment');
        var userPayment = parseFloat(userPaymentInput.value);
        var userBalance = parseFloat(document.getElementById('userBalance').innerText);
        var errorMessage = document.getElementById('errorMessage');

        if (userPaymentInput.value === '' || isNaN(userPayment)) {
            errorMessage.innerText = 'Error: Please enter a valid payment amount.';
        } else if (userPayment === 0) {
            errorMessage.innerText = 'Error: Payment amount cannot be zero.';
        } else if (userPayment > userBalance) {
            errorMessage.innerText = 'Error: Insufficient funds.';
        } else {
            errorMessage.innerText = '';
            $.ajax({
                url: '/Finance/Accept',
                type: 'PUT',
                data: JSON.stringify(userPayment),
                contentType: 'application/json; charset=utf-8',
                success: function () {
                    window.location.href = '/Finance/History';
                },
                error: function () {
                    errorMessage.innerText = 'Error: Unable to accept payment.';
                }
            });
        }
    }
</script>


<style>
    body {
        font-family: 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif;
        text-align: center;
        color: #777;
    }

    body h1 {
        font-weight: 300;
        margin-bottom: 0px;
        padding-bottom: 0px;
        color: #000;
    }

    body h3 {
        font-weight: 300;
        margin-top: 10px;
        margin-bottom: 20px;
        font-style: italic;
        color: #555;
    }

    body a {
        color: #06f;
    }

    .invoice-box {
        max-width: 800px;
        margin: auto;
        padding: 30px;
        border: 1px solid #eee;
        background-color: white;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.15);
        font-size: 16px;
        line-height: 24px;
        font-family: 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif;
        color: #555;
    }

    .invoice-box table {
        width: 100%;
        line-height: inherit;
        text-align: left;
        border-collapse: collapse;
    }

    .invoice-box table td {
        padding: 5px;
        vertical-align: top;
    }

    .invoice-box table tr td:nth-child(2) {
        text-align: right;
    }

    .invoice-box table tr.top table td {
        padding-bottom: 20px;
    }

    .invoice-box table tr.top table td.title {
        font-size: 45px;
        line-height: 45px;
        color: #333;
    }

    .invoice-box table tr.information table td {
        padding-bottom: 40px;
    }

    .invoice-box table tr.heading td {
        background: #eee;
        border-bottom: 1px solid #ddd;
        font-weight: bold;
    }

    .invoice-box table tr.details td {
        padding-bottom: 20px;
    }

    .invoice-box table tr.item td {
        border-bottom: 1px solid #eee;
    }

    .invoice-box table tr.item.last td {
        border-bottom: none;
    }

    .invoice-box table tr.total td:nth-child(2) {
        border-top: 2px solid #eee;
        font-weight: bold;
    }
</style>

FinanceApp.Presentation/Views/Finance/History.cshtml
@model IEnumerable<Bill>
@{
    bool isAdmin = base.User.IsInRole("Admin");

}


@if (!Model.Any())
{
    <h1 class="text-center" style="padding-top: 300px; color: #fff">There is no finances!</h1>
}
else
{
<form id="searchForm">
    <input type="text" id="searchInput" placeholder="Search by abonent number..." />
    <button type="submit">Search</button>
</form>
    <ul class="get-all-ul text-center" style="padding-top: 75px;">
        @foreach (var item in Model)
        {
            <div class="card">
                <span style="margin-top: 20px;">Date: @item.PayDate</span>
                <span>Username: @item.User.UserName</span>
                <span>Email: @item.User.Email</span>
                <span>Amount Spent: @item.AmountSpent</span>
                <button class="abonent"
                    onclick="redirectToAction('/Identity/ProfileByAbonentNumber?AbonentNumber= @item.User.AbonentNumber')">Abonent
                    Number: @item.User.AbonentNumber</button>
                @if (isAdmin)
                {
                    <button class="edit" onclick="redirectToAction('/Finance/Update?id=@item.Id')">Edit</button>
                    <button class="delete" style="margin-bottom: 10px;"
                        onclick="redirectToAction('/Finance/Delete?id=@item.Id')">Delete</button>
                }
                <br />
            </div>
        }
    </ul>
}

<script>
    document.getElementById('searchForm').addEventListener('submit', function (event) {
        event.preventDefault();

        var abonentNumber = document.getElementById('searchInput').value;

        window.location.href = '/Finance/SearchByAbonentNumber?abonentNumber=' + abonentNumber;
    });
</script>

<style>
    .abonent {
        color: #fff;
        background-color: #274e91;
        transition: .3s;
    }

    .abonent:hover {
        background-color: #0c3274;
    }

    .edit {
        color: #fff;
        background-color: #918c27;
        transition: .3s;
    }

    .edit:hover {
        background-color: #787308;
    }

    .delete {
        color: #fff;
        background-color: #811313;
        transition: .3s;
    }

    .delete:hover {
        background-color: #710808;
    }

    .card {
        margin-top: 40px;
        background-color: #112e42;
        border-radius: 10px;
        width: 100%;
        align-items: center;
    }

    .card button {
        padding: 12px 20px;
        width: 500px;
        margin-top: 10px;
        border-radius: 5px;
    }

    .get-all-ul span {
        color: #fff;
        font-size: 20px;
    }

    .get-all-ul {
        display: flex;
        flex-direction: column;
        align-items: center;
    }
</style>

FinanceApp.Presentation/Views/Finance/Payment.cshtml
@model PaymentViewModel



<form class="payment-form" asp-action="Bill" asp-route-id="@Model.Service.Id" method="post">

    <div class="payment-div1">


        <img src="~/@Model.Service.ImageUrl"> <br>
        <button type="submit" class="btn btn-primary">Pay</button>

    </div>

    <div class="payment-div2">
        <span>
        Service Name:@Model.Service.Name<br>
           Name: @Model.User.UserName <br>
           Email: @Model.User.Email <br>
        </span>
    </div>

</form>



<style>
    .payment-form  {
        gap: 30px;
        position: absolute;
        display: flex;
        margin-top: 150px;
        flex-direction: row;
    }

    .payment-form img {
        height: 420px;
        width: 420px;
        
    }

    .payment-div1 {
        display: flex;
        flex-direction: column;

    }

    .payment-div2 {
        display: flex;
        flex-direction: column;
        font-size: 25px;
    }

     .payment-form button {
        margin-top: 20px;
        
    }

     .payment-div2 span {
       color: white;
       font-weight: bold;
       margin-top: 200px;

    }
</style>

FinanceApp.Presentation/Views/Finance/Services.cshtml
@model IEnumerable<Service>

@{
    ViewData["Title"] = "Services";
    bool isAdmin = base.User.IsInRole("Admin");

    string service = string.Empty;
}


@if (Model.Any() == false)
{
    <p class="text-white">Here is nothing</p>
}

<div class="services-div">
    <form asp-controller="Finance" asp-action="Search">
        <input type="text" name="service" placeholder="Search By Name . . ." />
        <button type="submit">Search</button>
    </form>

    @if (isAdmin)
    {
        <a class="add-service" asp-action="AddService" type="button">Add Service</a>
    }


    <div class="gallery">
        @foreach (var serviceItem in Model)
        {
            <p id="@serviceItem.Id">
                <a href="/Finance/Payment?id=@serviceItem.Id"><img src="~/@serviceItem.ImageUrl">
                </a>
                @if (isAdmin)
                {
                    <button class="deleteButton" onclick="DeleteService(@serviceItem.Id)">Delete Service</button>
                }
            </p>
        }
    </div>
</div>


<script>
    async function DeleteService(id) {
            await fetch('http://localhost:5074/Finance/DeleteUserService/' + id,
                {
                    method: 'DELETE'
                }).then(res => {
                    if (res.ok) {
                        let child = document.getElementById(id);

                        child.parentElement.removeChild(child);
                    } else if (res.status === 404) {
                        alert('Item not found.');
                    } else {
                        alert('Service cannot be deleted because it has bills');
                    }
                });
    };

</script>

<style>
    .deleteButton {
        margin-top: 10px;
        background-color: #dc3545;
        color: white;
        border: none;
        width: 200px;
        padding: 8px 20px;
        font-size: 16px;
        cursor: pointer;
        border-radius: 5px;
        transition: background-color 0.3s;
        box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
    }

    .deleteButton:hover {
        transition: 0.3s ease;
        background-color: #7a101b;
    }

    .deleteButton-container {
        margin-top: 10px;
    }
</style>

<style>
    .services-div {
        margin-top: 100px;
    }

    .services-div form input {
        width: 300px;
        padding: 10px 15px;
        border-radius: 10px;
        background-color: #ededed;
    }

    .services-div form button {
        height: 34px;
        border-radius: 10px;
        padding-left: 30px;
        padding-right: 30px;
        background-color: #28565ed6;
        color: #fff;
    }

    .services-div form button:hover {
        background-color: #0d4b55d6;
        transition: .2s ease;
    }

    .add-service {
        width: 400px;
        padding: 10px 15px;
        border-radius: 10px;
        text-align: center;
        color: #fff;
        text-decoration: none;
        margin-top: 10px;
        background-color: #112e42;
    }

    .add-service:hover {
        color: #fff;
        background-color: #002842;
        transition: .2s ease;
    }

    .gallery {
        display: grid;
        grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
        gap: 50px;
        margin: 50px 0 50px 80px;
    }

    .gallery img {
        border-radius: 10px;
        width: 200px;
        height: 200px;
    }

    .gallery img:hover {
        opacity: 0.8;
        transition: .1s;
    }
</style>

FinanceApp.Presentation/Views/Finance/Update.cshtml
@model Bill

<h1>Update Finance</h1>

<form asp-action="Update" method="post" class="ring">
    <i style="--clr:#00ff0a;"></i>
    <i style="--clr:#ff0057;"></i>
    <i style="--clr:#fffd44;"></i>
    <div class="login">
        <h2>Update</h2>
        <input asp-for="@Model.Id" hidden>
        <div class="inputBx">
            <input asp-for="@Model.PayDate" type="datetime-local">
        </div>
        <div class="inputBx">
            <input type="submit" value="Update">
        </div>
    </div>
</form>